apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: divaheuje-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:dd20f86f9cafaf572d68446f66435b69706b1ec2@sha256:ffe95f20d0b888aefcf82f28095fab3a96525b6d0b2d63567025e7f3a254cd9d
          name: container-image
